- hosts: localhost
  tasks:
  - name: include tripleo-modify-image
    import_role:
      name: tripleo-modify-image
    vars:
      tasks_from: rpm_install.yml
      source_image: {{ container_registry }}/{{ container_image_name }}:{{ '{{' }} image_tag {{ '}}' }}
      rpms_path: /tmp/hotfix/
      modified_append_tag: -hotfix-{{ bugzilla_number }}
